### ISSUE TITLE
Uniform distribution instead of random permutation

### ISSUE THREAD

**Issue by wilmar-thomas** [CCaribe9/SHAPEffects#1]
Hi,

First of all thank you for publishing the paper and for providing the code with it for reproducibility. While going through the code, I noticed a slight discrepancy (maybe intended) between the description of the algorithm and the actual routine.

In page 12, it says that :

> The algorithm is divided into two phases, a preliminary and optional
phase and the main component. In the first preprocessing phase, a random
variable is introduced into the dataset, specifically, a permutation of the most
influential variable according to the mean of the absolute values of the Shapley
values between the original variables.

However, in the function ``introduce_random_variable``, a uniform distribution is sampled from the most influential variable:

```
sample_train = np.random.uniform(low=random_variable_train.min(), high=random_variable_train.max(), size=(len(X_train),))
sample_val = np.random.uniform(low=random_variable_val.min(), high=random_variable_val.max(), size=(len(X_val),))
```

Following the paper definition, it should be:
```
sample_train = np.random.permutation(random_variable_train)
sample_val = np.random.uniform(random_variable_val)
```

I doubt that it has a big impact on results but I wanted to check with you nonethless whether it is intended or not. Happy to hear your thoughts.

Thanks,
Thomas

**Comment by CCaribe9** [comment]
Hi,

First of all, thank you for noticing. Indeed, what the paper says is not being done and should be changed (and will be changed) as you propose. Still, the effect of this modification should be minimal. The intention of that whole fragment is to introduce a random feature that has no relationship with the target variable. That way you can measure the importance of a feature that you know in advance that has no real relationship with the target to be predicted. The construction of this feature as indicated in the paper or with any other criteria should not have any impact, since all procedures would result in an unnecessary explanatory variable.

As I say, we will change the code and the results of the paper if they change considerably, which would surprise us.

Carlos

**Comment by wilmar-thomas** [comment]
hi Carlos, thanks for your reply. Indeed I would assume it's not material at all. Thanks for bringing an answer nonetheless
